# Generated by Django 2.2.4 on 2019-08-16 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menus',
            name='description',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
