# Generated by Django 2.2.4 on 2019-08-16 19:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0002_auto_20190816_0656'),
    ]

    operations = [
        migrations.AddField(
            model_name='menus',
            name='number',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='menus',
            name='description',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='menus',
            name='type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='menu.Type'),
        ),
    ]
